CREATE TABLE public.instagram_posts_test (
	id varchar NOT NULL,
	inputurl varchar NULL,
	"type" varchar NULL,
	shortcode varchar NULL,
	caption varchar NULL,
	url varchar NULL,
	commentscount int4 NULL,
	dimensionsheight int4 NULL,
	dimensionswidth int4 NULL,
	displayurl varchar NULL,
	videourl varchar NULL,
	alt varchar NULL,
	likescount int4 NULL,
	videoviewcount int4 NULL,
	videoplaycount int4 NULL,
	"timestamp" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	locationname varchar NULL,
	locationid varchar NULL,
	ownerfullname varchar NULL,
	ownerusername varchar NULL,
	ownerid varchar NULL,
	producttype varchar NULL,
	videoduration float8 NULL,
	issponsored bool NULL,
	musicinfo json NULL,
	hashtags json NULL,
	mentions json NULL,
	images json NULL,
	childposts json NULL,
	taggedusers json NULL,
	coauthorproducers json NULL,
	CONSTRAINT instagram_posts_test_pkey PRIMARY KEY (id)
);